apiVersion: v1
kind: Namespace
metadata:
  name: robusta-pre-req
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pre-req-runner-cluster-role
  namespace: robusta-pre-req
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - daemonsets
      - deployments
      - events
      - namespaces
      - persistentvolumes
      - persistentvolumeclaims
      - pods
      - pods/status
      - pods/exec
      - pods/log
      - replicasets
      - replicationcontrollers
      - services
      - serviceaccounts
      - endpoints
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - persistentvolumes
      - persistentvolumeclaims
      - pods
      - pods/status
      - pods/exec
      - pods/log
      - pods/eviction
    verbs:
      - delete
      - create
      - patch
      - update

  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create

  - apiGroups:
      - "apiregistration.k8s.io"
    resources:
      - apiservices
    verbs:
      - get
      - list

  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "autoscaling"
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - patch
      - update

  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - patch
      - delete

  - apiGroups:
      - apps
    resources:
      - daemonsets
      - statefulsets
    verbs:
      - patch

  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - ingresses
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
      - patch
      - delete
      - create

  - apiGroups:
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - get
      - list

  - apiGroups:
      - networking.k8s.io
    resources:
    - ingresses
    - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
    - horizontalpodautoscalers
    verbs:
      - get
      - list
  - apiGroups:
      - "policy"
    resources:
    - poddisruptionbudgets
    - podsecuritypolicies
    verbs:
      - get
      - list
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
    - clusterroles
    - clusterrolebindings
    - roles
    - rolebindings
    verbs:
      - get
      - list

#{{- if .Values.openshift.enabled }}
#  - apiGroups:
#    - security.openshift.io
#    resources:
#    - securitycontextconstraints
#    verbs:
#    - use
#    resourceNames:
#    - {{ if .Values.openshift.createScc }}"pre-req-scc"{{ else }}{{ .Values.openshift.sccName | quote }}{{ end }}
#  - apiGroups:
#    - monitoring.coreos.com
#    resources:
#    - servicemonitors
#    - prometheusrules
#    - alertmanagers
#    - podmonitors
#    verbs:
#    - get
#    - list
#    - watch
#    - create
#    - update
#    - patch
#    - delete
#    - deletecollection
#{{- if .Values.openshift.createPrivilegedScc }}
#    - pre-req-scc-privileged
#{{- end }}
#{{- if .Values.openshift.privilegedSccName }}
#    - {{ .Values.openshift.privilegedSccName }}
#{{- end }}
#{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pre-req-runner-service-account
  namespace: robusta-pre-req
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pre-req-runner-cluster-role-binding
  namespace: robusta-pre-req
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pre-req-runner-cluster-role
subjects:
  - kind: ServiceAccount
    name: pre-req-runner-service-account
    namespace: robusta-pre-req